### ISSUE TITLE
Add missing email domains

### ISSUE THREAD

**Issue by vilkoalexander** [derhuerst/email-providers#14]
Hey 🙂 

I updated the very root of this library by adding missed domains. Here's merged  [PR](https://github.com/goware/emailproviders/pull/8) 
Could you update this [repo](https://github.com/derhuerst/emailproviders) from the upstream?

**Comment by derhuerst** [comment]
Thanks for contributing. Fixed as of f3d713f800dbe58abf2b3b4a236f221788d5896c, published as `email-providers@1.14.0`.
