### ISSUE TITLE
error email-providers@2.0.0: The engine "node" is incompatible with this module. Expected version ">=18".

### ISSUE THREAD

**Issue by capaj** [derhuerst/email-providers#16]
why does this package need node 18?

**Comment by derhuerst** [comment]
As explained in https://github.com/derhuerst/email-providers/issues/15#issuecomment-1277820901, there is a reason (albeit small) why I require Node `>= 18`.

You can keep using `email-providers@^1.14` which requires Node `>= 6`, there haven't been frequent updates to the package *anyways* in the recent past.

Sorry.
