### ISSUE TITLE
all.json is not present

### ISSUE THREAD

**Issue by Kikobeats** [derhuerst/email-providers#2]
I don't see it in the repository 😢

**Comment by derhuerst** [comment]
The npm package contains it.

**Comment by Kikobeats** [comment]
🤔

**Comment by AoDev** [comment]
Any reason to not have the list in the repo?

**Comment by derhuerst** [comment]
I don't have it in the GitHub repo because it's an artefact generated from another data source, so I don't want to keep it in version control.

If you want to access the data with other tools than npm/Yarn, you can use https://unpkg.com/email-providers/all.json .

**Comment by AoDev** [comment]
@derhuerst Cool, thanks, and thanks for the list.
